import { ourKits } from "../src/assets/Our_Kits/ourKits.js";

export const products = [
    {
        id: 1,
        name: "Aaklan Wonder Kit",
        tagline: "Begin Your Robotics Journey",
        description: "Perfect for beginners and young innovators. Everything you need to start your robotics adventure with block-based programming.",
        image: ourKits.yellow_kit,
        price: "₹2,240",
        originalPrice: "₹2,690",
        rating: 4,
        slug: "aaklan-wonder-kit",
        features: [
            "Block-Based Programming",
            "10+ Robotics Projects",
            "PictoBlox Compatible",
            "Beginner Friendly (Age 8+)",
        ],
        category: "Beginner",
        stock: 15,
        discount: 17,
    },
    {
        id: 2,
        name: "Aaklan Nexus Kit",
        tagline: "Advanced Robotics Platform",
        description: "Professional grade robotics kit for makers and educators. Enhanced sensors and expanded capabilities for complex projects.",
        image: ourKits.Red_Kit_box,
        price: "₹3,590",
        originalPrice: "₹4,490",
        rating: 5,
        slug: "aaklan-nexus-kit",
        features: [
            "Text-Based Programming",
            "20+ Advanced Projects",
            "Wi-Fi & Bluetooth",
            "Arduino IDE Support",
        ],
        category: "Advanced",
        stock: 8,
        discount: 20,
    },
    {
        id: 3,
        name: "Leela Microcontroller Board",
        tagline: "The Ultimate Development Board",
        description: "Standalone Leela board for custom projects. Perfect for Arduino enthusiasts and professional developers.",
        image: ourKits.Leeka_Packed_Box,
        price: "₹1,790",
        originalPrice: "₹2,240",
        rating: 4,
        slug: "leela-arduino-board",
        features: [
            "Arduino Compatible",
            "ESP32 Processor",
            "Multiple I/O Ports",
            "Compact Design",
        ],
        category: "Development",
        stock: 25,
        discount: 20,
    },
];